name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
        features:
          - default
          - alloc
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build
        run: cargo build --workspace --features ${{ matrix.features }}
      - name: Test
        run: cargo test --workspace --features ${{ matrix.features }}
      - name: Run linter
        run: cargo clippy --workspace --features ${{ matrix.features }} -- -D warnings

  no_std:
    name: no_std Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build without std
        run: cargo build --workspace --no-default-features --features alloc
      - name: Test without std
        run: cargo test --workspace --no-default-features --features alloc

  formatting:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check formatting
        run: cargo fmt --all -- --check
